#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubio'

require 'optparse'
backend = 'cvlc'
debug = false
opt = OptionParser.new
opt.on('--vlc') { backend = 'cvlc' }
opt.on('--mpg123') { backend = 'mpg123' }
opt.on('--backend CMD') { |b| backend = b }
opt.on('--debug') { debug = true }
opt.on('--help') do
  puts opt
  exit
end
opt.on('--version') do
  puts Rubio::VERSION
  exit
end
opt.parse!(ARGV)

radio = Rubio::Radio.new(backend, debug: debug)
begin
  radio.launch
rescue StandardError => e
  radio&.player&.stop_all
  raise e
end
