#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubio'
require 'optparse'

options = { backend: 'vlc -I dummy' }

opt = OptionParser.new
opt.summary_width = 23
opt.on('--vlc', 'use VLC media player on the backend [default]') { options[:backend] = 'vlc -I rc' }
opt.on('--mpg123', 'Use mpg123 on the backend') { options[:backend] = 'mpg123' }
opt.on('--backend STR', String, 'command to use as back-end player') { |b| options[:backend] = b }
opt.on('--count INT', Numeric, 'number of stations to fetch from radio-browser') { |c| options[:radio_station_count] = c }
opt.on('--per-page INT', Numeric, 'number of stations per page') { |c| options[:table_per_page] = c }
opt.on('--[no-]page-count', TrueClass, 'show/hide page count') { |b| options[:show_page_count] = b }
opt.on('--width INT', Numeric, 'main window width') { |w| options[:initial_width] = w }
opt.on('--height INT', Numeric, 'main window height') { |h| options[:initial_height] = h }
opt.on('--[no-]menu', TrueClass, 'show/hide menu') { |b| options[:visible_menu] = b }
opt.on('--debug', 'output status of monitored threads') { options[:debug] = true }
opt.on('--help', 'show this help message') do
  puts opt
  exit
end
opt.on('--version', 'Show the rubio version number') do
  puts Rubio::VERSION
  exit
end

begin
  opt.parse!(ARGV)
rescue OptionParser::InvalidOption, OptionParser::AmbiguousOption
  puts opt
  exit
end

begin
  Rubio::Radio.launch(**options)
rescue StandardError => e
  Rubio::Radio.launched_application&.player&.stop_all
  raise e
end
