#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubio'
require 'optparse'

options = {backend: 'vlc -I dummy'}

opt = OptionParser.new
opt.on('--vlc') { options[:backend] = 'vlc -I rc' }
opt.on('--mpg123') { options[:backend] = 'mpg123' }
opt.on('--backend CMD') { |b| options[:backend] = b }
opt.on('--count RADIO_STATION_COUNT') { |c| options[:radio_station_count] = c }
opt.on('--width WINDOW_WIDTH') { |w| options[:initial_width] = w }
opt.on('--height WINDOW_HEIGHT') { |h| options[:initial_height] = h }
opt.on('--debug') { options[:debug] = true }
opt.on('--no-menu') { options[:visible_menu] = false }
opt.on('--help') do
  puts opt
  exit
end
opt.on('--version') do
  puts Rubio::VERSION
  exit
end
opt.parse!(ARGV)

Rubio::Radio.launch(**options)
